export const data = [
  {
    id: 1,
    order: 0,
    src: "https://i.ibb.co/rbDh1vX/image-1.webp",
    isFeature: true,
    isSelected: false,
  },
  {
    id: 2,
    order: 0,
    src: "https://i.ibb.co/JC1JDQR/image-11.jpg",
    isFeature: false,
    isSelected: false,
  },
  {
    id: 3,
    order: 0,
    src: "https://i.ibb.co/cgLWyBN/image-2.webp",
    isFeature: false,
    isSelected: false,
  },
  {
    id: 4,
    order: 0,
    src: "https://i.ibb.co/510RfQr/image-3.webp",
    isFeature: false,
    isSelected: false,
  },
  {
    id: 5,
    order: 0,
    src: "https://i.ibb.co/Kmz2wRH/image-4.webp",
    isFeature: false,
    isSelected: false,
  },
  {
    id: 6,
    order: 0,
    src: "https://i.ibb.co/JsKJsQX/image-5.webp",
    isFeature: false,
    isSelected: false,
  },
  {
    id: 7,
    order: 0,
    src: "https://i.ibb.co/0CWC8wx/image-6.webp",
    isFeature: false,
    isSelected: false,
  },
  {
    id: 8,
    order: 0,
    src: "https://i.ibb.co/9nBxHmq/image-7.webp",
    isFeature: false,
    isSelected: false,
  },
  {
    id: 9,
    order: 0,
    src: "https://i.ibb.co/RSzH8cX/image-8.webp",
    isFeature: false,
    isSelected: false,
  },
  {
    id: 10,
    order: 0,
    src: "https://i.ibb.co/3v3SdgT/image-9.webp",
    isFeature: false,
    isSelected: false,
  },
  {
    id: 11,
    order: 0,
    src: "https://i.ibb.co/Gs4G5K2/image-10.jpg",
    isFeature: false,
    isSelected: false,
  },
  // Add more images here
]